//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18444
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace resxar.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProgramMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProgramMessage() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("resxar.Resources.ProgramMessage", typeof(ProgramMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   拡張 DLL 読み込み時に予期しない問題が発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string exception_message_extension_dll_loading_error {
            get {
                return ResourceManager.GetString("exception_message_extension_dll_loading_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータ（{0}）の指定に問題があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string exception_message_illegal_parameter {
            get {
                return ResourceManager.GetString("exception_message_illegal_parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力ディレクトリ（{0}）が存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string exception_message_input_directory_not_found {
            get {
                return ResourceManager.GetString("exception_message_input_directory_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   拡張DLL（{0}）に問題があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string exception_message_invalid_extension_dll {
            get {
                return ResourceManager.GetString("exception_message_invalid_extension_dll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータ（{0}）が不足しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string exception_message_parameter_is_missing {
            get {
                return ResourceManager.GetString("exception_message_parameter_is_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーションアーカイバーの初期化時に予期しない問題が発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string exception_message_resource_archiver_initialize_error {
            get {
                return ResourceManager.GetString("exception_message_resource_archiver_initialize_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   使い方（標準）:
        ///    resxar
        ///        /in:入力ルートディレクトリ名
        ///        /out:出力ファイル名
        ///        [/checkTimestamp:タイムスタンプチェック可否(true or false, 省略時は true)]
        ///        [/encoding:テキストファイルの文字コード]
        ///        [/bitmap:Bitmap保存可否(true or false, 省略時は true)]
        ///
        ///    入力ディレクトリ配下の全てのファイルをリソースとして取り込み、
        ///    resx ファイル形式で出力ファイルに出力します。
        ///
        ///    リソースの取り込みルールは以下の通りです。
        ///
        ///    リソースの名前:
        ///        以下の構成で名前が決まります。
        ///         [拡張子_入力ルートディレクトリからの相対パス_ファイル名]
        ///        ただし「.」およびパス区切りは「_」で置換されます。
        ///        また、先頭が数字になる場合は接頭子として「_」が１文字加えられます。
        ///        これはリソースに ResXF [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string usage {
            get {
                return ResourceManager.GetString("usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定したリソースアーカイバーの説明: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string usage_resource_archiver_header {
            get {
                return ResourceManager.GetString("usage_resource_archiver_header", resourceCulture);
            }
        }
    }
}
